set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'andreasvc/vim-256noir'
Plugin 'tpope/vim-surround'
Plugin 'leafgarland/typescript-vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Put your non-Plugin stuff after this line

colorscheme 256_noir

set background=dark
set t_Co=256

set cursorline
set wildmenu
set number
set directory=$HOME/.vim/swp//
set hlsearch

nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4

au FileType markdown setlocal spell spelllang=en_us

" Journal
function! AddJournalTimestamp()
	execute 'normal gg'
	let timestamp = '#' . ' ' . strftime('%A, %d %b %Y')
	call setline(1, timestamp)
	execute 'normal G'
	execute 'normal o'
endfunction

augroup templates
	au!

	au BufNewFile */journal/**/*.md 0r ~/.vim/templates/today.skeleton
	au BufNewFile */journal/**/*.md call AddJournalTimestamp()

	au BufNewFile *.svelte 0r ~/.vim/templates/svelte.skeleton
augroup end

syntax on
au BufReadPost *.svelte set syntax=html

