call plug#begin('~/.vim/plugged')
call plug#end()

set t_Co=256
syntax enable

set cursorline
set wildmenu
set number
set directory=$HOME/.vim/swp//
set hlsearch
set tabstop=2 shiftwidth=2 expandtab

nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4

au FileType markdown setlocal spell spelllang=en_us

